---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
library(shiny)
```


```{r, include = FALSE}
data("instacart")
head(instacart)

instacart = instacart %>% 
  filter(department == "produce") %>% 
  sample_n(5000)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Order Items from Each Department were Added to Cart

```{r}
instacart %>% 
  plot_ly(x = ~aisle, y = ~add_to_cart_order, color = ~aisle,
          alpha = 0.5,
          type = "box") %>% 
  layout(xaxis = list(title = "Aisle"),
         yaxis = list(title = "Order Items Were Added to Cart"))
```

Column {data-width=500}
-----------------------------------------------------------------------

### Most Popular Items

```{r}
instacart %>% 
  group_by(product_name) %>%
  mutate(count = n()) %>% 
  distinct(product_name, .keep_all = TRUE) %>% 
  filter(count > 60) %>% 
  mutate(product_name = fct_reorder(product_name, count)) %>% 
  plot_ly(x = ~reorder(product_name, -count), y = ~count,
          alpha = 0.5,
          type = "bar") %>% 
  layout(margin = list(b = 100),
         xaxis = list(title = "Product Name"),
         yaxis = list(title = "Count"))
```

### Order Number and Days Since Previous Order

```{r}
instacart %>% 
  filter(add_to_cart_order == 1) %>% 
  plot_ly(x = ~order_number, y = ~days_since_prior_order, color = ~aisle,
          type = "scatter") %>% 
  layout(xaxis = list(title = "Order Number"),
         yaxis = list(title = "Days Since Previous Order"))
```
